input {
  tcp {
    port => 5044
    codec => json
  }
  beats {
    port => 5045
  }
}

filter {
  if [message] {
    mutate {
      add_field => { "received_at" => "%{@timestamp}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
